import Link from "next/link"
import { ArrowRight, CheckCircle2 } from "lucide-react"
import { PageHero } from "@/components/page-hero"
import { Section, SectionHeader } from "@/components/section"
import { RevealOnScroll } from "@/components/reveal-on-scroll"
import { QuoteCTA } from "@/components/quote-cta"
import { services } from "@/lib/data"
export const metadata={title:"Technology Services",description:"ASYX core service pillars across smart technology, telematics, cybersecurity, software, ICT infrastructure and managed services."}
export default function Services(){return <><PageHero label="Core service pillars" title="Design. Deploy. Operate. Support." subtitle="Nine capability areas, structured to solve technology and operational requirements end to end." bgImage="/asyx/smart-tech.jpg"/><Section><RevealOnScroll><SectionHeader eyebrow="Our capabilities" title="Built around the full technology lifecycle." description="Select a service pillar to see the scope ASYX provides."/></RevealOnScroll><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{services.map((s,i)=><RevealOnScroll key={s.slug} delay={i*50}><Link href={s.cta.href} className="group block h-full overflow-hidden rounded-2xl border border-border bg-card transition hover:-translate-y-1 hover:shadow-xl"><div className="aspect-[16/9] overflow-hidden"><img src={s.image} alt="" className="size-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-6"><h2 className="text-xl font-semibold">{s.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{s.description}</p><ul className="mt-5 space-y-2">{s.items.slice(0,4).map(x=><li key={x} className="flex gap-2 text-sm text-muted-foreground"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-primary"/>{x}</li>)}</ul><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary">View capability <ArrowRight className="size-4"/></span></div></Link></RevealOnScroll>)}</div></Section><QuoteCTA/></>}
